# -----------------------------------------------------------------------------
# © 2026 Artalor
# Artalor Project — All rights reserved.
# Licensed for personal and educational use only.
# Commercial use or redistribution prohibited.
# See LICENSE.md for full terms.
# -----------------------------------------------------------------------------

from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from typing import List
import sys
import os

# Add infrastructure layer to path
sys.path.append(os.path.join(os.path.dirname(__file__), '../../modules'))
from modules.nodes.chat_node import ChatNode

# 1. Output data structure definition
class AdStoryboardFrame(BaseModel):
    frame_id: int = Field(description="Frame number")
    scene_type: str = Field(description="Scene type: opening/product_showcase/lifestyle/ending")
    duration: str = Field(description="Duration")
    first_image_description: str = Field(description="First frame image description - must include user's actual product")
    last_image_description: str = Field(description="Last frame image description - must include user's actual product")
    video_description: str = Field(description="Video action description")
    camera_movement: str = Field(description="Camera movement")
    text_overlay: str = Field(description="Text overlay content")
    transition: str = Field(description="Transition effect")

class AdStoryboardResult(BaseModel):
    total_frames: int = Field(description="Total number of frames")
    total_duration: str = Field(description="Total duration")
    visual_theme: str = Field(description="Visual theme")
    storyboard_frames: List[AdStoryboardFrame] = Field(description="Advertisement storyboard frames list")

# 2. Dynamic prompt template function
def create_ad_storyboard_template(target_duration: int = 30, video_duration_per_clip: float = 5.0) -> ChatPromptTemplate:
    """
    Create ad storyboard template with dynamic frame count based on duration
    
    Args:
        target_duration: Target total video duration in seconds (default: 30)
        video_duration_per_clip: Duration of each video clip generated by the model (default: 5.0)
    
    Returns:
        ChatPromptTemplate configured for the target duration
    """
    # Calculate number of frames needed based on video model's clip duration
    # Each frame will be one video clip
    num_frames = max(3, min(7, int(target_duration / video_duration_per_clip + 0.5)))  # Round to nearest, clamp to 3-7
    
    # Calculate duration per frame (should approximately equal video_duration_per_clip)
    duration_per_frame = target_duration / num_frames
    
    template_text = f"""
You are a professional advertisement storyboard designer. Based on the advertisement script and product analysis, design detailed advertisement storyboard script.

⚠️ **CRITICAL AUDIO REQUIREMENT - READ FIRST** ⚠️
The video generation model will create videos WITH audio. You MUST specify ONLY ambient/environmental sounds in your descriptions.
- ✅ ALLOWED AUDIO: footsteps, wind, water flowing, paper rustling, fabric sounds, product interaction sounds, ambient room tone
- ❌ STRICTLY FORBIDDEN: human voice, narration, speech, music, BGM, singing, voiceover, talking
- WHY: The final video will have professional voiceover and BGM added separately in post-production
- CONSEQUENCE: If you include narration/music in video descriptions, the final result will have overlapping audio tracks

Advertisement script:
- Opening: {{hook}}
- Main content: {{main_content}}
- Call to action: {{call_to_action}}
- Visual notes: {{visual_notes}}

Product features:
- Product category: {{product_category}}
- Visual style: {{visual_style}}
- Core selling points: {{selling_points}}
- Color scheme: {{color_palette}}

**CRITICAL PRODUCT REFERENCE** (All frames MUST maintain exact product consistency):
{{reference_image_context}}

**⚠️ MANDATORY REQUIREMENT - PRODUCT CONSISTENCY**:
The user has provided ACTUAL PRODUCT IMAGE(S). You MUST:
1. Use the EXACT product described in the reference images above
2. Maintain IDENTICAL visual characteristics: shape, color, material, distinctive features
3. DO NOT create, modify, or imagine a different product
4. DO NOT change product colors, shape, branding, or any visual features
5. Every frame description must reference specific product features from the analysis above

**CRITICAL**: Design EXACTLY {num_frames} storyboards (total duration: ~{target_duration} seconds).

IMPORTANT: Each storyboard frame will be converted into a single video clip that is approximately {video_duration_per_clip:.1f} seconds long.
Therefore, allocate approximately {duration_per_frame:.1f} seconds per frame.

Typical structure (adjust based on {num_frames} frames):

1. **Opening Storyboard (Opening)**:
   - Attention-grabbing opening scene
   - Can show usage scenarios or problem situations
   - Set the stage for product appearance
   - Duration: ~{duration_per_frame:.1f} seconds

2. **Product Showcase Storyboard (Product Showcase)**:
   - **Core requirement: Display the user's actual product**
   - Highlight product's key features and selling points
   - Multi-angle product detail display
   - **Audio**: ONLY product sounds (e.g., rustling, clicking, fabric movement) - NO music, NO voice
   - Duration: ~{duration_per_frame:.1f} seconds

3. **Lifestyle Storyboard (Lifestyle)** (if {num_frames} >= 4):
   - Show product effects in actual usage scenarios
   - **Must include the user's real product**
   - Reflect product value and experience
   - Duration: ~{duration_per_frame:.1f} seconds

4. **Ending Storyboard (Ending)**:
   - Brand display and call to action
   - **Display the user's product again**
   - Strengthen purchase intention
   - Duration: ~{duration_per_frame:.1f} seconds

Each storyboard includes:
- **Scene Type**: Clear functional positioning of the storyboard
- **Duration**: Specific time allocation (~{duration_per_frame:.1f} seconds per frame, total ~{target_duration} seconds)
- **First Frame Description**: Detailed static scene description
  * MUST explicitly mention the EXACT product with its specific features from reference
  * MUST include: product shape, color, distinctive features, material, brand elements
  * Example: "A brown leather LV handbag with gold hardware and monogram pattern..."
- **Last Frame Description**: Scene at the end of storyboard (CRITICAL: This is the target end state)
  * MUST explicitly mention the EXACT product with its specific features from reference
  * MUST maintain all product characteristics from first frame
  * Example: "The same brown leather LV handbag with gold hardware, now held by model..."
- **Video Description**: Dynamic changes from first to last frame
  * CRITICAL: Must describe the motion/transition that leads to the EXACT scene in "Last Frame Description"
  * The video's final frame MUST match the "Last Frame Description" precisely
  * Focus on: camera movement, subject motion, lighting changes
  * Example: "Camera slowly pushes in on the handbag while model's hand reaches to pick it up, ending in the exact pose described in last frame"
  * **AUDIO REQUIREMENT**: Only ambient/environmental sounds (NO narration, NO background music, NO voiceover)
    - Examples of good audio: footsteps, wind, water flowing, paper rustling, fabric sounds, product interaction sounds
    - Examples of bad audio: human voice, narration, music, BGM, singing
- **Camera Movement**: Camera techniques like push/pull/pan/tilt
- **Text Overlay**: Copy content to be added
- **Transition Effect**: Connection with next storyboard

**Key Principles**:
1. **Product Consistency**: All storyboards must feature the same product provided by the user
2. **Visual Coherence**: Maintain unified overall visual style
3. **Rhythm Control**: Ensure tight and powerful advertisement rhythm
4. **Practicality**: Descriptions should be specific and executable for AI generation
5. **Duration Accuracy**: MUST generate EXACTLY {num_frames} frames, each ~{duration_per_frame:.1f} seconds, totaling ~{target_duration} seconds
6. **Video Model Compatibility**: Each frame will become a {video_duration_per_clip:.1f}-second video clip
7. **Audio Guidelines**: Video descriptions should ONLY reference ambient/environmental sounds
   - ✅ ALLOWED: footsteps, wind, water, paper rustling, fabric movement, product interaction sounds
   - ❌ FORBIDDEN: human voice, narration, music, BGM, singing, voiceover
   - The final video will have separate voiceover and BGM tracks added in post-production
"""
    
    return ChatPromptTemplate.from_template(template_text)

# Keep default template for backward compatibility
AD_STORYBOARD_TEMPLATE = create_ad_storyboard_template(30, 5.0)

# 3. Business component class  
class AdStoryboardDesigner:
    """Advertisement storyboard design business component - self-contained node, template, structure"""
    
    # Input-output mapping configuration
    INPUT_MAPPING = {
        'hook': ['ad_hook', 'hook', 'opening'],
        'main_content': ['ad_main_content', 'main_content', 'content'],
        'call_to_action': ['ad_cta', 'call_to_action', 'cta'],
        'visual_notes': ['ad_visual_notes', 'visual_notes'],
        'product_category': ['analyzed_category', 'product_category', 'category'],
        'visual_style': ['product_style', 'visual_style', 'style'],
        'selling_points': ['selling_points', 'key_benefits'],
        'color_palette': ['colors', 'color_palette', 'primary_colors'],
        'reference_image_descriptions': ['reference_image_descriptions'],
        'target_duration': ['target_duration'],  # Target total video duration
        'video_duration_per_clip': ['video_duration_per_clip']  # Duration per video clip from model
    }
    
    OUTPUT_MAPPING = {
        'storyboard_frames': 'ad_storyboard',  # Maintain compatibility
        'total_frames': 'frame_count',
        'total_duration': 'duration',
        'visual_theme': 'theme'
    }
    
    @classmethod
    def create_node(cls, name: str, task_path: str, **config) -> ChatNode:
        """Factory method: create advertisement storyboard design node"""
        node = ChatNode(name, task_path)
        
        # Configure node
        node.prompt_template = AD_STORYBOARD_TEMPLATE
        node.output_structure = AdStoryboardResult
        
        # Custom run logic
        def custom_run(inputs):
            # Input mapping processing
            mapped_inputs = {}
            for target_field in cls.INPUT_MAPPING.keys():
                mapped_inputs[target_field] = cls._map_input(inputs, target_field)
            
            # Check required fields
            required_fields = ['hook', 'main_content', 'call_to_action']
            for field in required_fields:
                if not mapped_inputs[field]:
                    raise ValueError(f"Missing required field: {field}")
            
            # Process list type fields
            if isinstance(mapped_inputs['selling_points'], list):
                mapped_inputs['selling_points'] = ', '.join(mapped_inputs['selling_points'])
            if isinstance(mapped_inputs['color_palette'], list):
                mapped_inputs['color_palette'] = ', '.join(mapped_inputs['color_palette'])
            
            # Handle null values
            for key, value in mapped_inputs.items():
                if value is None:
                    mapped_inputs[key] = "Not provided"

            # Build detailed reference image context string for the prompt
            ref_ctx = "Not provided"
            rid = mapped_inputs.get('reference_image_descriptions')
            if isinstance(rid, list) and len(rid) > 0:
                try:
                    lines = []
                    for item in rid:
                        if isinstance(item, dict):
                            idx = item.get('index', '?')
                            lines.append(f"\n=== PRODUCT IMAGE {idx} - DETAILED ANALYSIS ===")
                            lines.append(f"Summary: {item.get('summary', 'N/A')}")
                            lines.append(f"Category: {item.get('product_category', 'N/A')}")
                            lines.append(f"Brand: {item.get('brand_info', 'N/A')}")
                            lines.append(f"Shape & Structure: {item.get('shape_structure', 'N/A')}")
                            lines.append(f"Color Scheme: {item.get('color_scheme', 'N/A')}")
                            lines.append(f"Material & Texture: {item.get('material_texture', 'N/A')}")
                            lines.append(f"Distinctive Features: {item.get('distinctive_features', 'N/A')}")
                            lines.append(f"Size & Proportion: {item.get('size_proportion', 'N/A')}")
                            elements = item.get('key_elements', [])
                            if isinstance(elements, list):
                                elements_str = ', '.join([str(e) for e in elements])
                            else:
                                elements_str = str(elements)
                            lines.append(f"Additional Elements: {elements_str}")
                            lines.append("=" * 50)
                        else:
                            lines.append(str(item))
                    ref_ctx = "\n".join(lines)
                except Exception as e:
                    ref_ctx = f"Provided but failed to parse: {str(e)}"
            mapped_inputs['reference_image_context'] = ref_ctx
            
            # Get target duration and video clip duration
            target_duration = mapped_inputs.get('target_duration')
            if target_duration is None or target_duration == "Not provided":
                target_duration = 30  # Default to 30 seconds
            else:
                try:
                    target_duration = int(target_duration)
                except (ValueError, TypeError):
                    target_duration = 30
            
            # Get video duration per clip from video model config
            video_duration_per_clip = mapped_inputs.get('video_duration_per_clip')
            if video_duration_per_clip is None or video_duration_per_clip == "Not provided":
                video_duration_per_clip = 5.0  # Default to 5 seconds
            else:
                try:
                    video_duration_per_clip = float(video_duration_per_clip)
                except (ValueError, TypeError):
                    video_duration_per_clip = 5.0
            
            # Create dynamic prompt template based on target duration and video clip duration
            dynamic_template = create_ad_storyboard_template(target_duration, video_duration_per_clip)
            
            # Call LLM with dynamic template
            result = (dynamic_template | node.chat_model.with_structured_output(node.output_structure)).invoke(mapped_inputs)
            
            # Output mapping processing  
            output = cls._map_output(result.model_dump())
            return output
        
        node.run = custom_run
        return node
    
    @classmethod
    def _map_input(cls, inputs: dict, target_field: str):
        """Input field mapping"""
        possible_fields = cls.INPUT_MAPPING.get(target_field, [target_field])
        for field in possible_fields:
            if field in inputs and inputs[field]:
                return inputs[field]
        return None
    
    @classmethod  
    def _map_output(cls, result: dict) -> dict:
        """Output field mapping"""
        mapped_result = {}
        for source_field, target_field in cls.OUTPUT_MAPPING.items():
            if source_field in result:
                mapped_result[target_field] = result[source_field]
        
        # Add additional compatibility mapping
        if 'storyboard_frames' in result:
            mapped_result['storyboard'] = result['storyboard_frames']  # Compatible with ImageNode
        
        return {**result, **mapped_result} 


# ============================================================================
# LangChain Agent Tool Version
# ============================================================================

from langchain_core.tools import BaseTool
from langchain_core.callbacks import CallbackManagerForToolRun
from typing import Optional
import json

class AdStoryboardDesignInput(BaseModel):
    """Input parameters for advertisement storyboard design tool"""
    hook: str = Field(description="Advertisement opening hook")
    main_content: str = Field(description="Advertisement main content")
    call_to_action: str = Field(description="Advertisement call to action")
    visual_notes: Optional[str] = Field(default=None, description="Visual presentation notes (optional)")
    product_category: Optional[str] = Field(default=None, description="Product category (optional)")
    visual_style: Optional[str] = Field(default=None, description="Visual style preference (optional)")
    selling_points: Optional[str] = Field(default=None, description="Key selling points (optional)")
    color_palette: Optional[str] = Field(default=None, description="Color palette (optional)")

class AdStoryboardDesignerTool(BaseTool):
    """Advertisement storyboard design tool - Create detailed ad storyboards for video production"""
    
    name: str = "ad_storyboard_designer"
    description: str = """
    Professional advertisement storyboard design tool. Creates detailed ad storyboards with:
    - Opening scene storyboards
    - Product showcase storyboards
    - Lifestyle demonstration storyboards
    - Ending/call-to-action storyboards
    - Frame-by-frame image descriptions
    - Video action descriptions
    - Camera movements and transitions
    - Text overlay specifications
    
    This tool creates production-ready storyboards optimized for advertisement video creation.
    """
    args_schema: type = AdStoryboardDesignInput
    
    def _run(
        self,
        hook: str,
        main_content: str,
        call_to_action: str,
        visual_notes: Optional[str] = None,
        product_category: Optional[str] = None,
        visual_style: Optional[str] = None,
        selling_points: Optional[str] = None,
        color_palette: Optional[str] = None,
        run_manager: Optional[CallbackManagerForToolRun] = None,
    ) -> str:
        """Execute advertisement storyboard design"""
        try:
            print(f"📺 [AdStoryboardDesignerTool] Starting ad storyboard design...")
            print(f"📺 [AdStoryboardDesignerTool] Hook: {hook[:50]}...")
            
            # Prepare input data
            input_data = {
                'hook': hook,
                'main_content': main_content,
                'call_to_action': call_to_action,
                'visual_notes': visual_notes or "Not provided",
                'product_category': product_category or "Not specified",
                'visual_style': visual_style or "Not specified",
                'selling_points': selling_points or "Not specified",
                'color_palette': color_palette or "Not specified"
            }
            
            # Create temporary node for ad storyboard design
            designer = AdStoryboardDesigner()
            node = designer.create_node("temp_ad_storyboard_designer", ".")
            
            # Execute storyboard design
            result = node.run(input_data)
            
            # Format storyboard frames for better readability
            frames_summary = []
            if 'storyboard_frames' in result:
                for frame in result['storyboard_frames']:
                    if isinstance(frame, dict):
                        frame_text = f"Frame {frame.get('frame_id', '?')} ({frame.get('scene_type', 'Unknown')}): {frame.get('duration', 'N/A')}"
                        frames_summary.append(frame_text)
                    else:
                        frames_summary.append(str(frame))
            
            # Format output for better readability
            formatted_result = {
                "storyboard_summary": f"Advertisement storyboard design completed with {result.get('total_frames', 0)} frames",
                "total_frames": result.get('total_frames', 0),
                "total_duration": result.get('total_duration', 'Not specified'),
                "visual_theme": result.get('visual_theme', 'Not specified'),
                "frames_summary": frames_summary,
                "production_ready": "Yes - includes detailed image and video descriptions for each frame",
                "raw_data": result  # Full data for other tools to use
            }

            try:
                scene_groups = {}
                for frame in result.get('storyboard_frames', []):
                    scene_type = frame.get('scene_type', 'unknown') if isinstance(frame, dict) else getattr(frame, 'scene_type', 'unknown')
                    scene_groups.setdefault(scene_type, []).append(frame)

                storyboards = []
                for idx, (scene_type, frames) in enumerate(scene_groups.items(), 1):
                    storyboards.append({
                        "storyboard_id": idx,
                        "scene_type": scene_type,
                        "frames": frames,
                        "frame_count": len(frames)
                    })

                formatted_result["storyboards"] = storyboards
                formatted_result["total_storyboards"] = len(storyboards)
            except Exception as _:
                formatted_result["storyboards"] = [
                    {
                        "storyboard_id": 1,
                        "scene_type": "combined",
                        "frames": result.get('storyboard_frames', []),
                        "frame_count": result.get('total_frames', 0)
                    }
                ]
                formatted_result["total_storyboards"] = 1
            # ----------------------------------------------------------------------

            # Return pure JSON string (no status prefix) so that downstream tools can parse without regex.
            print("📺 [AdStoryboardDesignerTool] Storyboard design completed")
            return json.dumps(formatted_result, ensure_ascii=False)
            
        except Exception as e:
            error_msg = f"❌ Error occurred during ad storyboard design: {str(e)}"
            print(f"📺 [AdStoryboardDesignerTool] {error_msg}")
            return error_msg 