# -----------------------------------------------------------------------------
# © 2026 Artalor
# Artalor Project — All rights reserved.
# Licensed for personal and educational use only.
# Commercial use or redistribution prohibited.
# See LICENSE.md for full terms.
# -----------------------------------------------------------------------------

# refactored_architecture/2_business_components/generation/storyboard_designer.py
from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from typing import List
import sys
import os

# Add infrastructure layer to path
sys.path.append(os.path.join(os.path.dirname(__file__), '../../modules'))
from modules.nodes.chat_node import ChatNode

# 1. Output data structure definition
class StoryboardFrame(BaseModel):
    frame_id: int = Field(description="Frame number")
    scene_summary: str = Field(description="Scene summary description")
    first_image_description: str = Field(description="First frame image description, detailed static scene")
    last_image_description: str = Field(description="Last frame image description, detailed static scene")
    video_description: str = Field(description="Video action description, from first to last frame dynamics")
    camera_movement: str = Field(description="Camera movement description")
    duration: str = Field(description="Duration")
    transition: str = Field(description="Transition effect")

class StoryboardResult(BaseModel):
    total_frames: int = Field(description="Total number of frames")
    overall_style: str = Field(description="Overall visual style")
    storyboard_frames: List[StoryboardFrame] = Field(description="Storyboard frames list")

# 2. Dynamic prompt template function
def create_story_storyboard_template(target_duration: int = 60, video_duration_per_clip: float = 8.0) -> ChatPromptTemplate:
    """
    Create story storyboard template with dynamic frame count based on duration
    
    Args:
        target_duration: Target total video duration in seconds (default: 60)
        video_duration_per_clip: Duration of each video clip generated by the model (default: 8.0)
    
    Returns:
        ChatPromptTemplate configured for the target duration
    """
    # Calculate number of frames needed based on video model's clip duration
    num_frames = max(3, min(8, int(target_duration / video_duration_per_clip + 0.5)))  # Round to nearest, clamp to 3-8
    
    # Calculate duration per frame
    duration_per_frame = target_duration / num_frames
    
    duration_per_frame_str = f"{duration_per_frame:.1f}"
    clip_duration_str = f"{video_duration_per_clip:.1f}"
    
    template_text = """
You are a professional storyboard designer and video director. Based on the provided story content and scene analysis, please design a detailed storyboard script.

Original story:
{story_content}

Scene analysis:
{scene_descriptions}

Visual style suggestion:
{visual_style}

**CRITICAL**: Design EXACTLY NUM_FRAMES storyboards (total duration: ~TARGET_DURATION seconds).

IMPORTANT: Each storyboard frame will be converted into a single video clip that is approximately CLIP_DURATION seconds long.
Therefore, allocate approximately DURATION_PER_FRAME seconds per frame.

Please design storyboards according to the following requirements:

1. **Overall Planning**:
   - Create EXACTLY NUM_FRAMES storyboards to match the target duration
   - Establish overall visual style and color tone
   - Each frame should be approximately DURATION_PER_FRAME seconds

2. **Each Storyboard Design**:
   - **Scene Summary**: Concisely summarize what this storyboard expresses
   - **First Frame Description**: Detailed description of static composition, elements, lighting, etc.
   - **Last Frame Description**: Detailed description of the static scene at the end of this storyboard
   - **Video Description**: Describe the dynamic changes from first to last frame
   - **Camera Movement**: Explain camera movement methods (push/pull/pan/tilt, close-up/wide shot, etc.)
   - **Duration**: Should be approximately DURATION_PER_FRAME seconds
   - **Transition Effect**: Connection method with the next storyboard

3. **Image Description Requirements**:
   - First and last frame descriptions should be detailed enough to guide AI image generation
   - Include specific visual elements: character expressions, object details, environmental atmosphere, lighting effects
   - Descriptions should be specific and clear, avoiding abstract concepts
   - Maintain visual consistency of the scenes

4. **Dynamic Description Requirements**:
   - Video descriptions should clearly explain dynamic changes
   - Include character actions, object movements, environmental changes, etc.
   - Consider technical feasibility of video generation

Example format:
- First frame: A character stands at the scene entrance, warm light illuminating their features, background setting clearly established with rich environmental details
- Last frame: The character moves deeper into the scene, lighting shifts to reflect the changing mood, key visual elements transform to show progression
- Video: The character moves through the scene with purposeful action, camera follows smoothly, environmental details shift naturally, lighting transitions to match the emotional arc
"""
    # Use .replace() for numeric values to avoid f-string escaping issues with ChatPromptTemplate's {braces}
    template_text = (template_text
        .replace('NUM_FRAMES', str(num_frames))
        .replace('TARGET_DURATION', str(target_duration))
        .replace('CLIP_DURATION', clip_duration_str)
        .replace('DURATION_PER_FRAME', duration_per_frame_str))
    
    return ChatPromptTemplate.from_template(template_text)

# Legacy static template (kept for backward compatibility)
STORYBOARD_TEMPLATE = create_story_storyboard_template()

# 3. Business component class
class StoryboardDesigner:
    """Storyboard design business component - self-contained node, template, structure"""
    
    # Input-output mapping configuration
    INPUT_MAPPING = {
        'story_content': ['story', 'story_content', 'story_text', 'content'],
        'scene_descriptions': ['scene', 'scene_descriptions', 'scenes', 'analyzed_scenes'],
        'visual_style': ['visual_style', 'visual_style_suggestion', 'style'],
        'target_duration': ['target_duration'],  # Target total video duration
        'video_duration_per_clip': ['video_duration_per_clip']  # Duration per video clip from model
    }
    
    OUTPUT_MAPPING = {
        'storyboard_frames': 'storyboard',  # Maintain compatibility
        'total_frames': 'frame_count',
        'overall_style': 'final_style'
    }
    
    @classmethod
    def create_node(cls, name: str, task_path: str, **config) -> ChatNode:
        """Factory method: create storyboard design node"""
        node = ChatNode(name, task_path)
        
        # Configure node (template will be created dynamically in custom_run)
        node.output_structure = StoryboardResult
        
        # Custom run logic
        def custom_run(inputs):
            # Input mapping processing
            story_content = cls._map_input(inputs, 'story_content')
            scene_descriptions = cls._map_input(inputs, 'scene_descriptions')
            visual_style = cls._map_input(inputs, 'visual_style')
            
            if not scene_descriptions:
                raise ValueError("No scene descriptions found in inputs")
            
            # Get target duration and video clip duration from inputs
            target_duration = cls._map_input(inputs, 'target_duration')
            if target_duration is None:
                target_duration = 60  # Default to 60 seconds
            else:
                try:
                    target_duration = int(target_duration)
                except (ValueError, TypeError):
                    target_duration = 60
            
            video_duration_per_clip = cls._map_input(inputs, 'video_duration_per_clip')
            if video_duration_per_clip is None:
                video_duration_per_clip = 8.0  # Default to 8 seconds
            else:
                try:
                    video_duration_per_clip = float(video_duration_per_clip)
                except (ValueError, TypeError):
                    video_duration_per_clip = 8.0
            
            # Create dynamic prompt template based on target duration and video clip duration
            dynamic_template = create_story_storyboard_template(target_duration, video_duration_per_clip)
            
            # Format scene descriptions
            if isinstance(scene_descriptions, list):
                scene_text = '\n'.join([f"{i+1}. {scene}" for i, scene in enumerate(scene_descriptions)])
            else:
                scene_text = str(scene_descriptions)
            
            # Call LLM with dynamic template
            result = (dynamic_template | node.chat_model.with_structured_output(node.output_structure)).invoke({
                'story_content': story_content or 'Not provided',
                'scene_descriptions': scene_text,
                'visual_style': visual_style or 'Not specified'
            })
            
            # Output mapping processing  
            output = cls._map_output(result.model_dump())
            return output
        
        node.run = custom_run
        return node
    
    @classmethod
    def _map_input(cls, inputs: dict, target_field: str):
        """Input field mapping"""
        possible_fields = cls.INPUT_MAPPING.get(target_field, [target_field])
        for field in possible_fields:
            if field in inputs and inputs[field]:
                return inputs[field]
        return None
    
    @classmethod  
    def _map_output(cls, result: dict) -> dict:
        """Output field mapping"""
        mapped_result = {}
        for source_field, target_field in cls.OUTPUT_MAPPING.items():
            if source_field in result:
                mapped_result[target_field] = result[source_field]
        
        return {**result, **mapped_result} 


# ============================================================================
# LangChain Agent Tool Version
# ============================================================================

from langchain_core.tools import BaseTool
from langchain_core.callbacks import CallbackManagerForToolRun
from typing import Optional
import json

class StoryboardDesignInput(BaseModel):
    """Input parameters for storyboard design tool"""
    scene_descriptions: str = Field(description="Scene descriptions or story breakdown")
    visual_style: Optional[str] = Field(default=None, description="Visual style preference (optional)")

class StoryboardDesignerTool(BaseTool):
    """Storyboard design tool - Create detailed storyboards for video production"""
    
    name: str = "storyboard_designer"
    description: str = """
    Professional storyboard design tool for video production. Creates detailed storyboards with:
    - Frame-by-frame scene breakdowns
    - First and last frame image descriptions
    - Video action descriptions
    - Camera movement specifications
    - Duration estimates
    - Transition effects
    
    This tool converts story scenes into production-ready storyboards for image and video generation.
    """
    args_schema: type = StoryboardDesignInput
    
    def _run(
        self,
        scene_descriptions: str,
        visual_style: Optional[str] = None,
        run_manager: Optional[CallbackManagerForToolRun] = None,
    ) -> str:
        """Execute storyboard design"""
        try:
            print(f"🎬 [StoryboardDesignerTool] Starting storyboard design...")
            print(f"🎬 [StoryboardDesignerTool] Scene descriptions: {scene_descriptions[:100]}...")
            
            # Prepare input data
            input_data = {
                'scene_descriptions': scene_descriptions,
                'visual_style': visual_style or "Create freely based on story content"
            }
            
            # Create temporary node for storyboard design
            designer = StoryboardDesigner()
            node = designer.create_node("temp_storyboard_designer", ".")
            
            # Execute storyboard design
            result = node.run(input_data)
            
            # Format storyboard frames for better readability
            frames_summary = []
            if 'storyboard_frames' in result:
                for frame in result['storyboard_frames']:
                    if isinstance(frame, dict):
                        frame_text = f"Frame {frame.get('frame_id', '?')}: {frame.get('scene_summary', '')}"
                        frames_summary.append(frame_text)
                    else:
                        frames_summary.append(str(frame))
            
            # Format output for better readability
            formatted_result = {
                "storyboard_summary": f"Storyboard design completed with {result.get('total_frames', 0)} frames",
                "total_frames": result.get('total_frames', 0),
                "overall_style": result.get('overall_style', 'Not specified'),
                "frames_summary": frames_summary,
                "production_ready": "Yes - includes detailed image and video descriptions",
                "raw_data": result  # Full data for other tools to use
            }
            
            success_msg = f"✅ Storyboard design completed successfully!\n{json.dumps(formatted_result, indent=2, ensure_ascii=False)}"
            print(f"🎬 [StoryboardDesignerTool] Storyboard design completed")
            return success_msg
            
        except Exception as e:
            error_msg = f"❌ Error occurred during storyboard design: {str(e)}"
            print(f"🎬 [StoryboardDesignerTool] {error_msg}")
            return error_msg 